hparams = {'batch_size': 64,
           'noise_dim': 64,
           'g_dim': 128,
           'g_depth': [2, 2, 1],
           'g_learning_rate': 0.0001,
           'g_beta_1': 0.0,
           'g_beta_2': 0.99,
           'd_dim': [32, 64],
           'd_depth': [1, 2],
           'd_learning_rate': 0.0001,
           'd_beta_1': 0.0,
           'd_beta_2': 0.99,
           'd_steps': 2,
           'loss': 'hinge'}
